name: ToDoApp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.9
  uuid: ^3.0.6
  provider: ^6.0.3
  drift: ^2.0.0
  path_provider: ^2.0.0
  sqflite: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  drift_dev: ^2.0.0
  build_runner: ^2.1.5



